### ISSUE TITLE
Enchancement:  2 new events

### ISSUE THREAD

**Issue by Kraken74** [Hekta/CHCitizens#2]
Hi, first of all, thanks for the CH extension.  I was wondering if it would be possible to create 2 new events?  
1- Event triggered when we right-click an NPC to control (ride) it.
2- Event triggered when we dismount an NPC.

Is that possible?

Thanks,
Happy new year!

**Comment by PseudoKnight** [comment]
Can you not get those events from player_interact_entity and vehicle_leave?

**Comment by Kraken74** [comment]
I've tried vehicle_leave and it seems to only trigger when leaving a minecart or boat.

**Comment by PseudoKnight** [comment]
Oh right.. I always forget there's a special event for non-vehicles: EntityDismountEvent.

**Comment by Kraken74** [comment]
Good to know, as it is not listed in the wiki.  Thanks, I will try this.

**Comment by PseudoKnight** [comment]
EntityDismountEvent is a Spigot event.

**Comment by Kraken74** [comment]
Ok, so it is not accessible from CH?

**Comment by PseudoKnight** [comment]
No. In theory I could have added it to CHSpigot, but I guess it could be added into CH since it's building against Spigot now.
